version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: todo-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-network  

  backend:
    build: ./backend
    container_name: todo-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo  # Ensure mongo starts before backend
    environment:
      MONGO_URI: mongodb://admin:password@mongo:27017/todo-db?authSource=admin
    networks:
      - todo-network

  frontend:
    build: ./frontend
    container_name: todo-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend  # Ensure backend starts before frontend
    networks:
      - todo-network

volumes:
  mongo-data:  # Ensure the volume for mongo is correctly defined

networks:
  todo-network:
    driver: bridge
